name: Deploy to Wiki
on:
  push:
    branches:
      - updates
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GitHub Wiki
        uses: sharkdp/github-wiki-publish@v1
        with:
          wiki-repo: ${{ github.repository }}.wiki.git
          commit-message: "Update Wiki"
          target-directory: "./examples/integrations/github-wiki/docs"
