name: Deploy Github Wiki
on:
  push:
    paths:
      - "integrations/github-wiki/docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload example to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "integrations/github-wiki/docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
