name: Update Wiki

on:
  push:
    paths:
      - "examples/04-typedoc-githun-wiki-theme/docs/**"
    branches:
      - restructure
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ineshbose/wiki-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIKI_DIR: "examples/core/04-typedoc-githun-wiki-theme/docs"
